### ISSUE TITLE
Add a PDF file with the schematics and top/bottom view of the 3D model of the PCB

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/daughterboards#12]
Example: [Schematic_OBDH_Eng_Model_2_ALT_v02.pdf](https://github.com/spacelab-ufsc/obdh2/blob/master/hardware/Schematic_OBDH_Eng_Model_2_ALT_v02.pdf)

**Comment by YanAzer** [comment]
Ontem fazendo o último documento do projeto (BOM) percebi que o resistor "RES 0R OHM 1/16W JUMPER 0805" usado tanto na OBDH Eng Model 2 como nesta placa filha não existe, pelo menos até onde pesquisei na Digi-Key e Mouser. O único package disponível para essa especificação de potência (1/16W) é o 0402, não achei nenhum que seja 0802 como especificado no Altium. @andrempmattos @mgm8

**Comment by YanAzer** [comment]
Encontrei o partnumber no altium como sendo este: CRCW08050000Z0EA, pesquisando os resultados aparecem com o valor mínimo de 1/8W tendo o package de 0802 @andrempmattos @mgm8

**Comment by YanAzer** [comment]
Ainda não consegui deixar o arquivo da BOM na Output Job File para pegar os parâmetros Do componente de memória e do cartão SD. Assim por enquanto atualizei manualmente neste commit https://github.com/spacelab-ufsc/daughterboards/commit/5777cbacb6b5473c9a48c96ffb7be911536bc317

**Comment by YanAzer** [comment]
Agora o arquivo da BOM gerado automaticamente pelo Output Job File está pegando todos os parâmetros da template menos da coluna "fitted". O componente "RES 0R OHM 1/16W JUMPER 0805" foi alterado por um do mesmo package (0805) com valor de potência 1/8W, mais especificamente este aqui (https://www.digikey.com/products/en?keywords=311-0.0ARCT-ND) que também possuímos em estoque.
